
; *****************************************************************
; STRING.S
; Storage for all strings in the game.
;
; Copyright (C) 2022 Aidan Garvey - see MAIN.S for license details.
; *****************************************************************

STR_INTRO:      DC.B 'INTRO SCREEN',0
STR_START:      DC.B 'PRESS START',0
STR_1P:         DC.B '1 PLAYER',0
STR_2P:         DC.B '2 PLAYERS',0
STR_OPTIONS:    DC.B 'OPTIONS',0
STR_MISSING:    DC.B 'COMING SOON',0
STR_CONTINUE:   DC.B 'CONTINUE',0
STR_QUIT:       DC.B 'QUIT',0
STR_PAUSE1:     DC.B 'P1 PAUSED',0
STR_PAUSE2:     DC.B 'P2 PAUSED',0
STR_DIFF:       DC.B 'SELECT DIFFICULTY',0
